### ISSUE TITLE
Define "tee"

### ISSUE THREAD

**Issue by yutakahirano** [yutakahirano/fetch-with-streams#14]
[Request.clone](https://fetch.spec.whatwg.org/#dom-request-clone) and [Response.clone](https://fetch.spec.whatwg.org/#dom-response-clone) have `tee` concept though it is not defined. It is not defined in the Stream spec either and I guess it won't be (@domenic, is that correct?) As introducing `body` grants users more controls, it should be specified more precisely in this spec.

**Comment by domenic** [comment]
I think the streams spec should probably define this, and eventually user-expose it. Since it is in the ship-ASAP subset, it sounds like I need to prioritize this highly. I will open an issue on whatwg/streams, but would welcome your contribution. I can't get around to it until next week due to TC39 this week.

**Comment by yutakahirano** [comment]
Thank you!

**Comment by yutakahirano** [comment]
We don't need a full algorithm for the first release, but specifying important points is desirable. The points being discussed in https://github.com/whatwg/streams/issues/271 need to be specified by the initial release, I think.

**Comment by yutakahirano** [comment]
Merged. https://github.com/yutakahirano/fetch-with-streams/commit/34d2ccc1fc3fb2a2ca92ef981a646d370c2cc496
