### ISSUE TITLE
Change type to ReadableStream

### ISSUE THREAD

**Issue by annevk** [yutakahirano/fetch-with-streams#46]
@domenic and @wanderview arrived at using `ReadableStream` for now. But we should have a note that indicates it might become `ReadableByteStream` if that path doesn't work out.

**Comment by domenic** [comment]
In particular, when we allow the constructors to take a `body` argument, we should make the note say something like "for now, you should not accept streams you did not create." This is part of leaving the door open to switch to ReadableByteStream.

I think we might also want to include some wiggle room in the spec for impls to continue shipping something named "ReadableByteStream" since this is still experimental territory and we're not sure what's exactly correct. I don't think Chrome is doing something wrong by keeping them separate for now.

Ultimate resolution will depend on how https://github.com/whatwg/streams/issues/379 goes.

**Comment by tyoshino** [comment]
https://github.com/whatwg/streams/issues/379 is done. Now ReadableStream is used for both byte source ones and non-byte source ones.

It's reflected to https://github.com/yutakahirano/fetch-with-streams/issues/63. I think we can close this.

**Comment by yutakahirano** [comment]
I'll fix the fetch spec later.

**Comment by annevk** [comment]
@yutakahirano it seems we never updated Fetch: https://fetch.spec.whatwg.org/#concept-body-stream.
