### ISSUE TITLE
Include some reference to the "lock" concept draft

### ISSUE THREAD

**Issue by tyoshino** [yutakahirano/fetch-with-streams#9]
Maybe @domenic's one?

**Comment by yutakahirano** [comment]
I created a branch https://github.com/yutakahirano/fetch-with-streams/tree/exclusive-reader to update the description around exclusive reader. Can you take a look?

**Comment by domenic** [comment]
I think it is pretty good. The only major thing is that "Let bytes be the result of reading from reader until it returns end-of-stream" is kind of vague, since it is mixing the concrete object of the reader with the implementation-specific idea of reading from reader to get "conceptual" bytes. Maybe something like:

"Let _bytes_ be the combined result of using implementation-specific mechanisms to repeatedly read from _stream_, using the exclusive access granted by _reader_, until the stream becomes closed or errored. If it becomes errored, reject _p_ with that error." What do you think? I do not think I am great at this kind of stuff, where we need to both leave implementations room to implement as they see fit, but also be conceptually precise. @annevk might have better ideas?

Other minor things:

- I would replace "Let _reader_ be an exclusive stream reader for _stream_" with "Let _reader_ be the result of acquiring an exclusive stream reader for _stream_" since that emphasizes that it is an active action instead of something that is passively there already.

- I might be able to help things be slightly more precise by creating precise definitions for you to link to for "locked to an exclusive reader" and "acquiring an exclusive stream reader". Maybe as abstract operations IsLockedToExclusiveReader(stream) and GetExclusiveStreamReader(stream).

- You should also handle what happens if getting an exclusive stream reader fails. Since the algorithm will be basically https://streams.spec.whatwg.org/#rs-get-reader, could happen in several scenarios: stream is closed, stream is errored, or stream is already locked to another reader. I would suggest removing the check if the stream is locked already, and then just handling GetExclusiveStreamReader(stream) failures and rejecting the promise with any thrown exception.

**Comment by annevk** [comment]
@domenic if we have a concept of a "stream" (on which a JavaScript API is layered) we can use that concept elsewhere, including its associated "read" and other concepts (see e.g. the Encoding Standard for an example of such a thing). Then we don't really have to talk about implementation details. The implementation just needs to meet the constraints of the concept.

**Comment by domenic** [comment]
I created an AcquireExclusiveStreamReader abstract operation you can link to: https://streams.spec.whatwg.org/#acquire-exclusive-stream-reader

**Comment by yutakahirano** [comment]
Addressed: https://github.com/yutakahirano/fetch-with-streams/tree/069860029708849793fa739cde5ac770b7a6a29a

 IsLockedToExclusiveReader would be great. I would use it if it is introduced.

**Comment by domenic** [comment]
Looks perfect to me. What would you use IsLockedToExclusiveReader for?

**Comment by yutakahirano** [comment]
> What would you use IsLockedToExclusiveReader for?

I thought about linking it from __bodyUsed__ definition.
